"""
blockchain.py
Handles all interactions with the Ethereum smart contract via Web3.py
"""

from web3 import Web3
import json, os

# ----------------------------------------------------------------
# CONNECTION SETUP
# Change the address below to the deployed FakeProduct contract address
# (printed after running:  truffle migrate  inside hello-eth/)
# ----------------------------------------------------------------
GANACHE_URL = "http://127.0.0.1:7545"
CONTRACT_ADDRESS = "0x7fB83F82A6728F2424853F5102471C6F8BF7ac8C"   # <-- UPDATE THIS

# Load ABI from compiled artifact (generated by truffle compile)
ABI_PATH = os.path.join(os.path.dirname(__file__),
                        "hello-eth", "build", "contracts", "FakeProduct.json")


def _load_abi():
    with open(ABI_PATH, "r") as f:
        artifact = json.load(f)
    return artifact["abi"]


def get_contract():
    """Return a connected Web3 contract instance. Compatible with Web3.py v5 and v6+"""
    w3 = Web3(Web3.HTTPProvider(GANACHE_URL))

    # connection check (v6 renamed isConnected → is_connected)
    try:
        connected = w3.is_connected()       # Web3.py v6+
    except AttributeError:
        connected = w3.isConnected()        # Web3.py v5

    if not connected:
        raise ConnectionError("Cannot connect to Ethereum node at " + GANACHE_URL)

    abi = _load_abi()

    # checksum address (v6 renamed toChecksumAddress → to_checksum_address)
    try:
        checksum_addr = Web3.to_checksum_address(CONTRACT_ADDRESS)   # v6+
    except AttributeError:
        checksum_addr = Web3.toChecksumAddress(CONTRACT_ADDRESS)     # v5

    contract = w3.eth.contract(address=checksum_addr, abi=abi)
    return w3, contract


def _wait_for_receipt(w3, tx_hash):
    """Wait for transaction receipt - compatible with v5 and v6+"""
    try:
        return w3.eth.wait_for_transaction_receipt(tx_hash)   # v6+
    except AttributeError:
        return w3.eth.waitForTransactionReceipt(tx_hash)      # v5


# ================================================================
# USER FUNCTIONS
# ================================================================

def add_user(username, password, email, contact):
    w3, contract = get_contract()
    tx_hash = contract.functions.addUser(username, password, email, contact).transact(
        {"from": w3.eth.accounts[0]}
    )
    _wait_for_receipt(w3, tx_hash)
    return True


def get_all_users():
    _, contract = get_contract()
    count = contract.functions.getUserCount().call()
    users = []
    for i in range(1, count + 1):
        u = contract.functions.getUser(i).call()
        users.append({
            "id": i,
            "username": u[0],
            "password": u[1],
            "email": u[2],
            "contact": u[3]
        })
    return users


def login_user(username, password):
    """Return user dict if credentials match, else None."""
    users = get_all_users()
    for u in users:
        if u["username"] == username and u["password"] == password:
            return u
    return None


# ================================================================
# PRODUCT FUNCTIONS
# ================================================================

def add_product(product_name, product_desc, product_price, barcode_signature):
    w3, contract = get_contract()
    tx_hash = contract.functions.addProduct(
        product_name, product_desc, product_price, barcode_signature
    ).transact({"from": w3.eth.accounts[0]})
    _wait_for_receipt(w3, tx_hash)
    product_id = contract.functions.getProductCount().call()
    return product_id


def get_product(product_id):
    _, contract = get_contract()
    try:
        p = contract.functions.getProduct(int(product_id)).call()
        return {
            "id": product_id,
            "productName": p[0],
            "productDesc": p[1],
            "productPrice": p[2],
            "barcodeSignature": p[3]
        }
    except Exception:
        return None


def get_all_products():
    _, contract = get_contract()
    count = contract.functions.getProductCount().call()
    products = []
    for i in range(1, count + 1):
        p = contract.functions.getProduct(i).call()
        products.append({
            "id": i,
            "productName": p[0],
            "productDesc": p[1],
            "productPrice": p[2],
            "barcodeSignature": p[3]
        })
    return products


def authenticate_barcode(product_id, input_signature):
    """Returns True if signature matches stored signature in blockchain."""
    _, contract = get_contract()
    try:
        return contract.functions.authenticate(int(product_id), input_signature).call()
    except Exception:
        return False